### ISSUE TITLE
Warum jetzt Weather API

### ISSUE THREAD

**Issue by TobyMaxham** [tamarillo/weather#1]
Ich dachte ihr wolltet diese nicht einbinden. Wir hatten uns 7:2 gegen die Integration der API im Core entschieden.

**Comment by DengoPHP** [comment]
Das steht hier nicht zur Diskussion. Die Weather API hat einen allgemeinen Nutzen. Darum wird sie entwickelt. Sie ist jedoch eigenständig und kein Core Modul. Es ist also für jeden die richtige Lösung
